### PR TITLE
🐛 Fix environemnt specific build configuration

### PR DESCRIPTION
**Pull request by jstorm31**
CRA's `--target` parameter only supports `production` value, not `development`, which results in console error with production build. As discussed [here](https://github.com/facebook/create-react-app/issues/790), custom env variable should be used for that. In our case `REACT_APP_BUILD_ENV`. 

I also fixed build commands naming so they correspond to the current Gitlba CI configuration.

### CODE REVIEW

**Review by horaklukas — APPROVED** [review]

**Comment by jstorm31** [comment]
I forgot to update `config.js` and `env.js` and set corrrect env variable there.

**Comment by cermakjiri** [comment]
Based on the `--target` param. `NODE_ENV` and `BUILD_ENV` were automatically set. If we're going to define `REACT_APP_BUILD_ENV ` before each build script, I'd suggest defining `NODE_ENV` before each build script as well and removing the `--target` completely. And so the `packages/react-scripts/custom/config/env.js` file can be then removed.

**Comment by jstorm31** [comment]
@cermakjiri Thank you for the feedback.

From [the documentation of CRA](https://create-react-app.dev/docs/adding-custom-environment-variables/):
> There is also a built-in environment variable called NODE_ENV. You can read it from process.env.NODE_ENV. When you run npm start, it is always equal to 'development', when you run npm test it is always equal to 'test', and when you run npm run build to make a production bundle, it is always equal to 'production'. You cannot override NODE_ENV manually. This prevents developers from accidentally deploying a slow development build to production.

So the `--target` param shouldn't affect it. Do you have any resource on that? Anyway it doesn't work for sure with `--target stage` as stated in the issue linked in the above description. There is even an error about production build in console when `--target development` is used.

So my conclusion to resolve the issue:

1. Is `BUILD_ENV` used for anything, how is it set and do we further need it?
2. We shouldn't set `NODE_ENV` manually, because it has always `production` value for `yarn build` and `development for `yarn start`.
3. We should remove `--target` as it clearly doesn't affect anything.
4. I don't agree with removing `config/env.js`. We define all `environments` used in code there and further export variables like `isEnvDevelopment`, etc. for convenience rather then always using `process.env.REACT_APP_BUILD_ENV`.

**Comment by cermakjiri** [comment]
> @cermakjiri Thank you for the feedback.
> 
> From [the documentation of CRA](https://create-react-app.dev/docs/adding-custom-environment-variables/):
> 
> > There is also a built-in environment variable called NODE_ENV. You can read it from process.env.NODE_ENV. When you run npm start, it is always equal to 'development', when you run npm test it is always equal to 'test', and when you run npm run build to make a production bundle, it is always equal to 'production'. You cannot override NODE_ENV manually. This prevents developers from accidentally deploying a slow development build to production.
> 
> So the `--target` param shouldn't affect it. Do you have any resource on that? Anyway it doesn't work for sure with `--target stage` as stated in the issue linked in the above description. There is even an error about production build in console when `--target development` is used.
> 
> So my conclusion to resolve the issue:
> 
> 1. Is `BUILD_ENV` used for anything, how is it set and do we further need it?
> 2. We shouldn't set `NODE_ENV` manually, because it has always `production` value for `yarn build` and `development for `yarn start`.
> 3. We should remove `--target` as it clearly doesn't affect anything.
> 4. I don't agree with removing `config/env.js`. We define all `environments` used in code there and further export variables like `isEnvDevelopment`, etc. for convenience rather then always using `process.env.REACT_APP_BUILD_ENV`.

1. Only here - `packages/react-scripts/custom/config/transformWebpackConfig.js` and it just needs to be replaced with `process.env.REACT_APP_BUILD_ENV`. 
2. Yes, make sense. 
3. Yes, I agree. It was created by me but it has turned out to not be as a good feature as I initially thought it will 😄 
4. Well the `packages/react-scripts/custom/config/env.js` was created by me and it can be safely removed. Don't misplace it with `config/env.js`, we definitely do not wanna remove that.

**Review by Tomas2D — APPROVED** [review]

**Comment by jstorm31** [comment]
Good, I updated `packages/react-scripts/custom/config/env.js` and `packages/react-scripts/custom/config/transformWebpackConfig.js` to use `REACT_APP_BUILD_ENV` and removed `--target` flag.

**Pull request merged**
