### PR TITLE
🎨 add install command, fix run tests

### PR DESCRIPTION
**Pull request by baierjak**
Added new install command to have it separatedly.

Also fix obsolete of running tests there and add flag for run lighthouse

### CODE REVIEW

**Review by jstorm31 — APPROVED** [review]

**Comment by cermakjiri** [comment]
Nepridal bys prosim jeste poznamku o zmene do changelogu obou templates?
- https://github.com/AckeeCZ/create-react-app/blob/master/packages/cra-template/CHANGELOG.md
- https://github.com/AckeeCZ/create-react-app/blob/master/packages/cra-template-typescript/CHANGELOG.md 
(Neni treba tam davat verzi, ani datum, staci Unreleased)

**Comment by baierjak** [comment]
> Nepridal bys prosim jeste poznamku o zmene do changelogu obou templates?
> 
> * https://github.com/AckeeCZ/create-react-app/blob/master/packages/cra-template/CHANGELOG.md
> * https://github.com/AckeeCZ/create-react-app/blob/master/packages/cra-template-typescript/CHANGELOG.md
>   (Neni treba tam davat verzi, ani datum, staci Unreleased)

Jop, dobry napad - pridam

**Comment by baierjak** [comment]
Vygeneroval jsem nove changelogy - jsou obrovske protoze to zpetne vygenerovalo vsechny predchozi verze :) funguje to fakt pekne

**Comment by cermakjiri** [comment]
- Ten jenkins upravim mimo tenhle MR, kvuli rebasu na posledni CRA verzi se nam trochu zvysil pocet zmen.
-  Changelogy generovat pomoci gitmoji-changelog by bylo fajn, ale chce to promyslet, jak to delat pro multi-repo. Takhle bychom meli vsechny zmeny v `packages/cra-template-typescript` 😄

**Pull request closed without merging**
